//! MlsSession — domain wrapper around openmls's MlsGroup, scoped to 1-on-1 conversations.

use crate::key_package::GHOST_CIPHERSUITE;
use crate::mls_credential::credential_with_key;
use crate::mls_provider::GhostMlsProvider;
use crate::{ProtoError, Result};
use ghost_identity::{DeviceKey, IdentityKey};
use openmls::prelude::*;
use openmls_basic_credential::SignatureKeyPair;
use openmls_traits::types::SignatureScheme;

pub struct MlsSession {
    group: MlsGroup,
}

impl MlsSession {
    /// Create a fresh MLS group containing only the creator. After this, call
    /// [`add_member`] to invite the conversation partner.
    pub fn create(provider: &GhostMlsProvider, ik: &IdentityKey, dk: &DeviceKey) -> Result<Self> {
        let (cwk, signer) = credential_with_key(provider, ik, dk)?;

        let group_config = MlsGroupCreateConfig::builder()
            .ciphersuite(GHOST_CIPHERSUITE)
            .use_ratchet_tree_extension(true)
            .build();

        let group = MlsGroup::new(provider, &signer, &group_config, cwk)
            .map_err(|e| ProtoError::Mls(format!("create group: {e}")))?;

        Ok(Self { group })
    }

    pub fn epoch(&self) -> u64 {
        self.group.epoch().as_u64()
    }

    /// Build a fresh signer for the given DK — convenience for tests and downstream callers
    /// that need a `SignatureKeyPair` reference but don't have one stored.
    pub fn signer_from_dk(dk: &DeviceKey) -> SignatureKeyPair {
        SignatureKeyPair::from_raw(
            SignatureScheme::ED25519,
            dk.secret_bytes().to_vec(),
            dk.public().to_bytes().to_vec(),
        )
    }
}

/// Result of inviting a new member: the Welcome (to be sent to the invitee out-of-band)
/// plus the Commit (which the inviter applies locally — handled inside this method).
pub struct InviteResult {
    pub welcome: MlsMessageOut,
    pub commit: MlsMessageOut,
}

impl MlsSession {
    /// Invite a new member by their KeyPackage. Produces a Welcome the invitee can use to join,
    /// and a Commit message that — in larger groups — would be broadcast to other members.
    /// In our 1-on-1 case there are no other members yet, so the Commit is mostly bookkeeping.
    ///
    /// openmls 0.8 `add_members` returns `(commit, welcome, Option<GroupInfo>)`.
    pub fn add_member(
        &mut self,
        provider: &GhostMlsProvider,
        signer: &SignatureKeyPair,
        invitee_kp: KeyPackage,
    ) -> Result<InviteResult> {
        let (commit, welcome, _group_info) = self
            .group
            .add_members(provider, signer, &[invitee_kp])
            .map_err(|e| ProtoError::Mls(format!("add member: {e}")))?;

        // Apply the membership change locally so our state advances to epoch 1.
        self.group
            .merge_pending_commit(provider)
            .map_err(|e| ProtoError::Mls(format!("merge commit: {e}")))?;

        Ok(InviteResult { welcome, commit })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mls_provider::new_provider;

    #[test]
    fn create_session_starts_at_epoch_zero() {
        let provider = new_provider();
        let ik = IdentityKey::generate();
        let dk = DeviceKey::generate(&ik);
        let session = MlsSession::create(&provider, &ik, &dk).unwrap();
        assert_eq!(session.epoch(), 0);
    }
}

#[cfg(test)]
mod add_member_tests {
    use super::*;
    use crate::key_package::generate_key_package;
    use crate::mls_provider::new_provider;

    #[test]
    fn add_member_advances_epoch() {
        let alice_provider = new_provider();
        let alice_ik = IdentityKey::generate();
        let alice_dk = DeviceKey::generate(&alice_ik);
        let mut alice = MlsSession::create(&alice_provider, &alice_ik, &alice_dk).unwrap();
        assert_eq!(alice.epoch(), 0);

        // Bob (separate provider — represents a separate process/machine).
        let bob_provider = new_provider();
        let bob_ik = IdentityKey::generate();
        let bob_dk = DeviceKey::generate(&bob_ik);
        let bob_kp = generate_key_package(&bob_provider, &bob_ik, &bob_dk).unwrap();

        let alice_signer = MlsSession::signer_from_dk(&alice_dk);
        let invite = alice
            .add_member(&alice_provider, &alice_signer, bob_kp)
            .unwrap();
        assert_eq!(alice.epoch(), 1);

        let _ = invite.welcome;
        let _ = invite.commit;
    }
}

impl MlsSession {
    /// Join an MLS group by processing a Welcome message. The matching KeyPackage's private
    /// init key must already be in `provider`'s storage (registered when the KeyPackage was
    /// generated by `generate_key_package`).
    pub fn join_via_welcome(provider: &GhostMlsProvider, welcome: MlsMessageIn) -> Result<Self> {
        let welcome = welcome
            .into_welcome()
            .ok_or_else(|| ProtoError::Mls("not a welcome message".into()))?;

        let join_config = MlsGroupJoinConfig::default();

        let staged = StagedWelcome::new_from_welcome(provider, &join_config, welcome, None)
            .map_err(|e| ProtoError::Mls(format!("staged welcome: {e}")))?;
        let group = staged
            .into_group(provider)
            .map_err(|e| ProtoError::Mls(format!("join via welcome: {e}")))?;

        Ok(Self { group })
    }
}

#[cfg(test)]
mod welcome_tests {
    use super::*;
    use crate::key_package::generate_key_package;
    use crate::mls_provider::new_provider;
    use openmls::prelude::tls_codec::{Deserialize as TlsDeserialize, Serialize as TlsSerialize};

    #[test]
    fn alice_invites_bob_bob_joins() {
        // Alice's side
        let alice_provider = new_provider();
        let alice_ik = IdentityKey::generate();
        let alice_dk = DeviceKey::generate(&alice_ik);
        let mut alice = MlsSession::create(&alice_provider, &alice_ik, &alice_dk).unwrap();

        // Bob's side
        let bob_provider = new_provider();
        let bob_ik = IdentityKey::generate();
        let bob_dk = DeviceKey::generate(&bob_ik);
        let bob_kp = generate_key_package(&bob_provider, &bob_ik, &bob_dk).unwrap();

        // Alice invites Bob.
        let alice_signer = MlsSession::signer_from_dk(&alice_dk);
        let invite = alice
            .add_member(&alice_provider, &alice_signer, bob_kp)
            .unwrap();

        // Serialize the welcome to bytes (the wire form Bob would receive),
        // then deserialize on Bob's side.
        let welcome_bytes = invite.welcome.tls_serialize_detached().unwrap();
        let welcome_in = MlsMessageIn::tls_deserialize(&mut welcome_bytes.as_slice()).unwrap();

        // Bob joins.
        let bob = MlsSession::join_via_welcome(&bob_provider, welcome_in).unwrap();

        // Both at epoch 1.
        assert_eq!(alice.epoch(), 1);
        assert_eq!(bob.epoch(), 1);
    }
}

impl MlsSession {
    /// Encrypt an application message. Returns the wire-bytes representation of the MLS message.
    pub fn encrypt_app_message(
        &mut self,
        provider: &GhostMlsProvider,
        signer: &SignatureKeyPair,
        plaintext: &[u8],
    ) -> Result<Vec<u8>> {
        use openmls::prelude::tls_codec::Serialize as _;
        let msg = self
            .group
            .create_message(provider, signer, plaintext)
            .map_err(|e| ProtoError::Mls(format!("create message: {e}")))?;
        msg.tls_serialize_detached()
            .map_err(|e| ProtoError::Mls(format!("serialize message: {e}")))
    }

    /// Decrypt an application message. Returns the plaintext bytes.
    pub fn decrypt_app_message(
        &mut self,
        provider: &GhostMlsProvider,
        wire_bytes: &[u8],
    ) -> Result<Vec<u8>> {
        use openmls::prelude::tls_codec::Deserialize as _;
        let mls_in = MlsMessageIn::tls_deserialize(&mut &wire_bytes[..])
            .map_err(|e| ProtoError::Mls(format!("deserialize: {e}")))?;
        let protocol_msg = mls_in
            .try_into_protocol_message()
            .map_err(|e| ProtoError::Mls(format!("not a protocol message: {e}")))?;

        let processed = self
            .group
            .process_message(provider, protocol_msg)
            .map_err(|e| ProtoError::Mls(format!("process message: {e}")))?;

        match processed.into_content() {
            ProcessedMessageContent::ApplicationMessage(app) => Ok(app.into_bytes()),
            _ => Err(ProtoError::Mls("expected ApplicationMessage".into())),
        }
    }
}

#[cfg(test)]
mod app_message_tests {
    use super::*;
    use crate::key_package::generate_key_package;
    use crate::mls_provider::new_provider;
    use openmls::prelude::tls_codec::{Deserialize as TlsDeserialize, Serialize as TlsSerialize};

    fn alice_and_bob_in_group() -> (
        (GhostMlsProvider, MlsSession, SignatureKeyPair),
        (GhostMlsProvider, MlsSession, SignatureKeyPair),
    ) {
        let alice_provider = new_provider();
        let alice_ik = IdentityKey::generate();
        let alice_dk = DeviceKey::generate(&alice_ik);
        let mut alice = MlsSession::create(&alice_provider, &alice_ik, &alice_dk).unwrap();
        let alice_signer = MlsSession::signer_from_dk(&alice_dk);

        let bob_provider = new_provider();
        let bob_ik = IdentityKey::generate();
        let bob_dk = DeviceKey::generate(&bob_ik);
        let bob_kp = generate_key_package(&bob_provider, &bob_ik, &bob_dk).unwrap();
        let bob_signer = MlsSession::signer_from_dk(&bob_dk);

        let invite = alice
            .add_member(&alice_provider, &alice_signer, bob_kp)
            .unwrap();
        let welcome_bytes = invite.welcome.tls_serialize_detached().unwrap();
        let welcome_in = MlsMessageIn::tls_deserialize(&mut welcome_bytes.as_slice()).unwrap();
        let bob = MlsSession::join_via_welcome(&bob_provider, welcome_in).unwrap();

        (
            (alice_provider, alice, alice_signer),
            (bob_provider, bob, bob_signer),
        )
    }

    #[test]
    fn alice_to_bob_round_trip() {
        let ((alice_p, mut alice, alice_s), (bob_p, mut bob, _)) = alice_and_bob_in_group();
        let wire = alice
            .encrypt_app_message(&alice_p, &alice_s, b"hello bob")
            .unwrap();
        let recovered = bob.decrypt_app_message(&bob_p, &wire).unwrap();
        assert_eq!(recovered, b"hello bob");
    }

    #[test]
    fn bob_to_alice_round_trip() {
        let ((alice_p, mut alice, _), (bob_p, mut bob, bob_s)) = alice_and_bob_in_group();
        let wire = bob
            .encrypt_app_message(&bob_p, &bob_s, b"hi alice")
            .unwrap();
        let recovered = alice.decrypt_app_message(&alice_p, &wire).unwrap();
        assert_eq!(recovered, b"hi alice");
    }

    #[test]
    fn tampered_ciphertext_is_rejected() {
        let ((alice_p, mut alice, alice_s), (bob_p, mut bob, _)) = alice_and_bob_in_group();
        let mut wire = alice
            .encrypt_app_message(&alice_p, &alice_s, b"data")
            .unwrap();
        let last = wire.len() - 1;
        wire[last] ^= 0xFF;
        // openmls triggers a debug_assert in debug builds on AEAD failure, which panics.
        // We use catch_unwind to treat either a panic or a returned Err as rejection.
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            bob.decrypt_app_message(&bob_p, &wire)
        }));
        match result {
            Err(_panic) => { /* openmls debug_assert fired — tampered bytes rejected */ }
            Ok(Err(_)) => { /* returned error — tampered bytes rejected */ }
            Ok(Ok(_)) => panic!("expected decryption to fail on tampered ciphertext"),
        }
    }
}
