//! MlsSession — domain wrapper around openmls's MlsGroup, scoped to 1-on-1 conversations.

use crate::key_package::GHOST_CIPHERSUITE;
use crate::mls_credential::credential_with_key;
use crate::mls_provider::GhostMlsProvider;
use crate::{ProtoError, Result};
use ghost_identity::{DeviceKey, IdentityKey};
use openmls::prelude::*;
use openmls_basic_credential::SignatureKeyPair;
use openmls_traits::types::SignatureScheme;

pub struct MlsSession {
    group: MlsGroup,
}

impl MlsSession {
    /// Create a fresh MLS group containing only the creator. After this, call
    /// [`add_member`] to invite the conversation partner.
    pub fn create(provider: &GhostMlsProvider, ik: &IdentityKey, dk: &DeviceKey) -> Result<Self> {
        let (cwk, signer) = credential_with_key(provider, ik, dk)?;

        let group_config = MlsGroupCreateConfig::builder()
            .ciphersuite(GHOST_CIPHERSUITE)
            .use_ratchet_tree_extension(true)
            .build();

        let group = MlsGroup::new(provider, &signer, &group_config, cwk)
            .map_err(|e| ProtoError::Mls(format!("create group: {e}")))?;

        Ok(Self { group })
    }

    pub fn epoch(&self) -> u64 {
        self.group.epoch().as_u64()
    }

    /// Build a fresh signer for the given DK — convenience for tests and downstream callers
    /// that need a `SignatureKeyPair` reference but don't have one stored.
    pub fn signer_from_dk(dk: &DeviceKey) -> SignatureKeyPair {
        SignatureKeyPair::from_raw(
            SignatureScheme::ED25519,
            dk.secret_bytes().to_vec(),
            dk.public().to_bytes().to_vec(),
        )
    }
}

/// Result of inviting a new member: the Welcome (to be sent to the invitee out-of-band)
/// plus the Commit (which the inviter applies locally — handled inside this method).
pub struct InviteResult {
    pub welcome: MlsMessageOut,
    pub commit: MlsMessageOut,
}

impl MlsSession {
    /// Invite a new member by their KeyPackage. Produces a Welcome the invitee can use to join,
    /// and a Commit message that — in larger groups — would be broadcast to other members.
    /// In our 1-on-1 case there are no other members yet, so the Commit is mostly bookkeeping.
    ///
    /// openmls 0.8 `add_members` returns `(commit, welcome, Option<GroupInfo>)`.
    pub fn add_member(
        &mut self,
        provider: &GhostMlsProvider,
        signer: &SignatureKeyPair,
        invitee_kp: KeyPackage,
    ) -> Result<InviteResult> {
        let (commit, welcome, _group_info) = self
            .group
            .add_members(provider, signer, &[invitee_kp])
            .map_err(|e| ProtoError::Mls(format!("add member: {e}")))?;

        // Apply the membership change locally so our state advances to epoch 1.
        self.group
            .merge_pending_commit(provider)
            .map_err(|e| ProtoError::Mls(format!("merge commit: {e}")))?;

        Ok(InviteResult { welcome, commit })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mls_provider::new_provider;

    #[test]
    fn create_session_starts_at_epoch_zero() {
        let provider = new_provider();
        let ik = IdentityKey::generate();
        let dk = DeviceKey::generate(&ik);
        let session = MlsSession::create(&provider, &ik, &dk).unwrap();
        assert_eq!(session.epoch(), 0);
    }
}

#[cfg(test)]
mod add_member_tests {
    use super::*;
    use crate::key_package::generate_key_package;
    use crate::mls_provider::new_provider;

    #[test]
    fn add_member_advances_epoch() {
        let alice_provider = new_provider();
        let alice_ik = IdentityKey::generate();
        let alice_dk = DeviceKey::generate(&alice_ik);
        let mut alice = MlsSession::create(&alice_provider, &alice_ik, &alice_dk).unwrap();
        assert_eq!(alice.epoch(), 0);

        // Bob (separate provider — represents a separate process/machine).
        let bob_provider = new_provider();
        let bob_ik = IdentityKey::generate();
        let bob_dk = DeviceKey::generate(&bob_ik);
        let bob_kp = generate_key_package(&bob_provider, &bob_ik, &bob_dk).unwrap();

        let alice_signer = MlsSession::signer_from_dk(&alice_dk);
        let invite = alice
            .add_member(&alice_provider, &alice_signer, bob_kp)
            .unwrap();
        assert_eq!(alice.epoch(), 1);

        let _ = invite.welcome;
        let _ = invite.commit;
    }
}

impl MlsSession {
    /// Join an MLS group by processing a Welcome message. The matching KeyPackage's private
    /// init key must already be in `provider`'s storage (registered when the KeyPackage was
    /// generated by `generate_key_package`).
    pub fn join_via_welcome(provider: &GhostMlsProvider, welcome: MlsMessageIn) -> Result<Self> {
        let welcome = welcome
            .into_welcome()
            .ok_or_else(|| ProtoError::Mls("not a welcome message".into()))?;

        let join_config = MlsGroupJoinConfig::default();

        let staged = StagedWelcome::new_from_welcome(provider, &join_config, welcome, None)
            .map_err(|e| ProtoError::Mls(format!("staged welcome: {e}")))?;
        let group = staged
            .into_group(provider)
            .map_err(|e| ProtoError::Mls(format!("join via welcome: {e}")))?;

        Ok(Self { group })
    }
}

#[cfg(test)]
mod welcome_tests {
    use super::*;
    use crate::key_package::generate_key_package;
    use crate::mls_provider::new_provider;
    use openmls::prelude::tls_codec::{Deserialize as TlsDeserialize, Serialize as TlsSerialize};

    #[test]
    fn alice_invites_bob_bob_joins() {
        // Alice's side
        let alice_provider = new_provider();
        let alice_ik = IdentityKey::generate();
        let alice_dk = DeviceKey::generate(&alice_ik);
        let mut alice = MlsSession::create(&alice_provider, &alice_ik, &alice_dk).unwrap();

        // Bob's side
        let bob_provider = new_provider();
        let bob_ik = IdentityKey::generate();
        let bob_dk = DeviceKey::generate(&bob_ik);
        let bob_kp = generate_key_package(&bob_provider, &bob_ik, &bob_dk).unwrap();

        // Alice invites Bob.
        let alice_signer = MlsSession::signer_from_dk(&alice_dk);
        let invite = alice
            .add_member(&alice_provider, &alice_signer, bob_kp)
            .unwrap();

        // Serialize the welcome to bytes (the wire form Bob would receive),
        // then deserialize on Bob's side.
        let welcome_bytes = invite.welcome.tls_serialize_detached().unwrap();
        let welcome_in = MlsMessageIn::tls_deserialize(&mut welcome_bytes.as_slice()).unwrap();

        // Bob joins.
        let bob = MlsSession::join_via_welcome(&bob_provider, welcome_in).unwrap();

        // Both at epoch 1.
        assert_eq!(alice.epoch(), 1);
        assert_eq!(bob.epoch(), 1);
    }
}

impl MlsSession {
    /// Encrypt an application message. Returns the wire-bytes representation of the MLS message.
    pub fn encrypt_app_message(
        &mut self,
        provider: &GhostMlsProvider,
        signer: &SignatureKeyPair,
        plaintext: &[u8],
    ) -> Result<Vec<u8>> {
        use openmls::prelude::tls_codec::Serialize as _;
        let msg = self
            .group
            .create_message(provider, signer, plaintext)
            .map_err(|e| ProtoError::Mls(format!("create message: {e}")))?;
        msg.tls_serialize_detached()
            .map_err(|e| ProtoError::Mls(format!("serialize message: {e}")))
    }

    /// Decrypt an application message. Returns the plaintext bytes.
    pub fn decrypt_app_message(
        &mut self,
        provider: &GhostMlsProvider,
        wire_bytes: &[u8],
    ) -> Result<Vec<u8>> {
        use openmls::prelude::tls_codec::Deserialize as _;
        let mls_in = MlsMessageIn::tls_deserialize(&mut &wire_bytes[..])
            .map_err(|e| ProtoError::Mls(format!("deserialize: {e}")))?;
        let protocol_msg = mls_in
            .try_into_protocol_message()
            .map_err(|e| ProtoError::Mls(format!("not a protocol message: {e}")))?;

        let processed = self
            .group
            .process_message(provider, protocol_msg)
            .map_err(|e| ProtoError::Mls(format!("process message: {e}")))?;

        match processed.into_content() {
            ProcessedMessageContent::ApplicationMessage(app) => Ok(app.into_bytes()),
            _ => Err(ProtoError::Mls("expected ApplicationMessage".into())),
        }
    }
}

impl MlsSession {
    /// Group ID as raw bytes — useful for keying persisted state.
    pub fn group_id_bytes(&self) -> Vec<u8> {
        self.group.group_id().as_slice().to_vec()
    }

    /// Current epoch number — alias for `epoch()`, named for clarity in persistence contexts.
    pub fn current_epoch(&self) -> u64 {
        self.epoch()
    }

    /// Serialize the full MLS session state (provider storage + group ID) to an opaque blob.
    ///
    /// The blob can be stored in ghost-storage's `state_blob` column and later passed to
    /// [`deserialize_state`] to reconstruct a fully functional `MlsSession`.
    ///
    /// Uses `MemoryStorage::serialize` (available via openmls' `test-utils` feature) to
    /// produce a compact binary representation of all key material, then wraps it with the
    /// group ID in a CBOR envelope.
    pub fn serialize_state(&self, provider: &GhostMlsProvider) -> crate::Result<Vec<u8>> {
        // Serialize the MemoryStorage to bytes.
        let mut storage_bytes: Vec<u8> = Vec::new();
        provider
            .storage()
            .serialize(&mut storage_bytes)
            .map_err(|e| ProtoError::Mls(format!("serialize storage: {e}")))?;

        let state = PersistedMlsState {
            storage_blob: storage_bytes,
            group_id: self.group_id_bytes(),
        };

        let mut buf = Vec::new();
        ciborium::into_writer(&state, &mut buf)
            .map_err(|e| ProtoError::CborEncode(e.to_string()))?;
        Ok(buf)
    }

    /// Restore an `MlsSession` from a blob produced by [`serialize_state`].
    ///
    /// Returns both the reconstructed provider (with all key material restored) and the session.
    /// The caller is responsible for keeping the provider alive alongside the session — they
    /// form a pair that must be used together.
    pub fn deserialize_state(blob: &[u8]) -> crate::Result<(GhostMlsProvider, Self)> {
        let state: PersistedMlsState = ciborium::from_reader(blob)
            .map_err(|e| ProtoError::CborDecode(e.to_string()))?;

        // Reconstruct MemoryStorage from the serialized blob.
        let restored_storage =
            openmls_rust_crypto::MemoryStorage::deserialize(&mut state.storage_blob.as_slice())
                .map_err(|e| ProtoError::Mls(format!("deserialize storage: {e}")))?;

        // Build a fresh provider, then replace its storage contents with the restored map.
        // MemoryStorage.values is pub RwLock<HashMap<..>>, so we can overwrite in-place.
        let provider = openmls_rust_crypto::OpenMlsRustCrypto::default();
        {
            let restored_map = restored_storage.values.into_inner().map_err(|e| {
                ProtoError::Mls(format!("restored storage lock poisoned: {e}"))
            })?;
            let mut dest = provider.storage().values.write().map_err(|e| {
                ProtoError::Mls(format!("provider storage lock poisoned: {e}"))
            })?;
            *dest = restored_map;
        }

        // Load the MlsGroup from the now-populated provider.
        let group_id = openmls::prelude::GroupId::from_slice(&state.group_id);
        let group = openmls::prelude::MlsGroup::load(provider.storage(), &group_id)
            .map_err(|e| ProtoError::Mls(format!("load group: {e}")))?
            .ok_or_else(|| ProtoError::Mls("group not found in restored storage".into()))?;

        Ok((provider, Self { group }))
    }
}

/// CBOR envelope for persisted MLS state.
///
/// Wraps the raw `MemoryStorage` bytes together with the group ID so that
/// `deserialize_state` knows which group to load after restoring the provider.
#[derive(serde::Serialize, serde::Deserialize)]
struct PersistedMlsState {
    /// Bytes produced by `MemoryStorage::serialize` — contains all MLS key material.
    storage_blob: Vec<u8>,
    /// Raw group ID bytes (`GroupId::as_slice()`), used to call `MlsGroup::load`.
    group_id: Vec<u8>,
}

#[cfg(test)]
mod app_message_tests {
    use super::*;
    use crate::key_package::generate_key_package;
    use crate::mls_provider::new_provider;
    use openmls::prelude::tls_codec::{Deserialize as TlsDeserialize, Serialize as TlsSerialize};

    fn alice_and_bob_in_group() -> (
        (GhostMlsProvider, MlsSession, SignatureKeyPair),
        (GhostMlsProvider, MlsSession, SignatureKeyPair),
    ) {
        let alice_provider = new_provider();
        let alice_ik = IdentityKey::generate();
        let alice_dk = DeviceKey::generate(&alice_ik);
        let mut alice = MlsSession::create(&alice_provider, &alice_ik, &alice_dk).unwrap();
        let alice_signer = MlsSession::signer_from_dk(&alice_dk);

        let bob_provider = new_provider();
        let bob_ik = IdentityKey::generate();
        let bob_dk = DeviceKey::generate(&bob_ik);
        let bob_kp = generate_key_package(&bob_provider, &bob_ik, &bob_dk).unwrap();
        let bob_signer = MlsSession::signer_from_dk(&bob_dk);

        let invite = alice
            .add_member(&alice_provider, &alice_signer, bob_kp)
            .unwrap();
        let welcome_bytes = invite.welcome.tls_serialize_detached().unwrap();
        let welcome_in = MlsMessageIn::tls_deserialize(&mut welcome_bytes.as_slice()).unwrap();
        let bob = MlsSession::join_via_welcome(&bob_provider, welcome_in).unwrap();

        (
            (alice_provider, alice, alice_signer),
            (bob_provider, bob, bob_signer),
        )
    }

    #[test]
    fn alice_to_bob_round_trip() {
        let ((alice_p, mut alice, alice_s), (bob_p, mut bob, _)) = alice_and_bob_in_group();
        let wire = alice
            .encrypt_app_message(&alice_p, &alice_s, b"hello bob")
            .unwrap();
        let recovered = bob.decrypt_app_message(&bob_p, &wire).unwrap();
        assert_eq!(recovered, b"hello bob");
    }

    #[test]
    fn bob_to_alice_round_trip() {
        let ((alice_p, mut alice, _), (bob_p, mut bob, bob_s)) = alice_and_bob_in_group();
        let wire = bob
            .encrypt_app_message(&bob_p, &bob_s, b"hi alice")
            .unwrap();
        let recovered = alice.decrypt_app_message(&alice_p, &wire).unwrap();
        assert_eq!(recovered, b"hi alice");
    }

    #[test]
    fn tampered_ciphertext_is_rejected() {
        let ((alice_p, mut alice, alice_s), (bob_p, mut bob, _)) = alice_and_bob_in_group();
        let mut wire = alice
            .encrypt_app_message(&alice_p, &alice_s, b"data")
            .unwrap();
        let last = wire.len() - 1;
        wire[last] ^= 0xFF;
        // openmls triggers a debug_assert in debug builds on AEAD failure, which panics.
        // We use catch_unwind to treat either a panic or a returned Err as rejection.
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            bob.decrypt_app_message(&bob_p, &wire)
        }));
        match result {
            Err(_panic) => { /* openmls debug_assert fired — tampered bytes rejected */ }
            Ok(Err(_)) => { /* returned error — tampered bytes rejected */ }
            Ok(Ok(_)) => panic!("expected decryption to fail on tampered ciphertext"),
        }
    }
}

#[cfg(test)]
mod state_persist_tests {
    use super::*;
    use crate::key_package::generate_key_package;
    use crate::mls_provider::new_provider;
    use openmls::prelude::tls_codec::{Deserialize as TlsDeserialize, Serialize as TlsSerialize};
    use openmls::prelude::MlsMessageIn;

    #[test]
    fn alice_serialize_deserialize_continue_messaging() {
        // --- Setup: Alice creates group, invites Bob ---
        let alice_provider = new_provider();
        let alice_ik = ghost_identity::IdentityKey::generate();
        let alice_dk = ghost_identity::DeviceKey::generate(&alice_ik);
        let mut alice = MlsSession::create(&alice_provider, &alice_ik, &alice_dk).unwrap();
        let alice_signer = MlsSession::signer_from_dk(&alice_dk);

        let bob_provider = new_provider();
        let bob_ik = ghost_identity::IdentityKey::generate();
        let bob_dk = ghost_identity::DeviceKey::generate(&bob_ik);
        let bob_kp = generate_key_package(&bob_provider, &bob_ik, &bob_dk).unwrap();
        let bob_signer = MlsSession::signer_from_dk(&bob_dk);

        let invite = alice
            .add_member(&alice_provider, &alice_signer, bob_kp)
            .unwrap();
        let welcome_bytes = invite.welcome.tls_serialize_detached().unwrap();
        let welcome_in = MlsMessageIn::tls_deserialize(&mut welcome_bytes.as_slice()).unwrap();
        let mut bob = MlsSession::join_via_welcome(&bob_provider, welcome_in).unwrap();

        // --- Warmup message before snapshot ---
        let wire = alice
            .encrypt_app_message(&alice_provider, &alice_signer, b"warmup")
            .unwrap();
        let _ = bob.decrypt_app_message(&bob_provider, &wire).unwrap();
        let pre_epoch = alice.current_epoch();

        // --- Snapshot Alice ---
        let alice_state_bytes = alice.serialize_state(&alice_provider).unwrap();

        // Drop Alice + her provider (simulate process restart).
        drop(alice);
        drop(alice_provider);

        // --- Restore Alice ---
        let (alice_provider_restored, mut alice_restored) =
            MlsSession::deserialize_state(&alice_state_bytes).unwrap();
        assert_eq!(alice_restored.current_epoch(), pre_epoch);

        // Re-store Alice's signer key into the restored provider so encrypt can find it.
        alice_signer
            .store(alice_provider_restored.storage())
            .map_err(|e| ProtoError::Mls(format!("re-store signer: {e}")))
            .unwrap();

        // --- Continue messaging: Alice (restored) -> Bob ---
        let wire2 = alice_restored
            .encrypt_app_message(&alice_provider_restored, &alice_signer, b"after restart")
            .unwrap();
        let recovered = bob.decrypt_app_message(&bob_provider, &wire2).unwrap();
        assert_eq!(recovered, b"after restart");

        // --- Continue messaging: Bob -> Alice (restored) ---
        let wire3 = bob
            .encrypt_app_message(&bob_provider, &bob_signer, b"bob reply")
            .unwrap();
        let recovered2 = alice_restored
            .decrypt_app_message(&alice_provider_restored, &wire3)
            .unwrap();
        assert_eq!(recovered2, b"bob reply");
    }

    #[test]
    fn round_trip_preserves_group_id_and_epoch() {
        let provider = new_provider();
        let ik = ghost_identity::IdentityKey::generate();
        let dk = ghost_identity::DeviceKey::generate(&ik);
        let session = MlsSession::create(&provider, &ik, &dk).unwrap();

        let original_group_id = session.group_id_bytes();
        let original_epoch = session.current_epoch();

        let blob = session.serialize_state(&provider).unwrap();

        let (provider2, session2) = MlsSession::deserialize_state(&blob).unwrap();
        let _ = provider2; // provider must stay alive

        assert_eq!(session2.group_id_bytes(), original_group_id);
        assert_eq!(session2.current_epoch(), original_epoch);
    }
}
