//! Composed libp2p NetworkBehaviour for Ghost.
//!
//! Combines: Kademlia (DHT), Identify (peer protocol info), RequestResponse (raw bytes).

use libp2p::{
    autonat, dcutr, identify,
    identity::Keypair,
    kad::{self, store::MemoryStore},
    ping, relay,
    request_response::{self, ProtocolSupport},
    swarm::NetworkBehaviour,
    PeerId, StreamProtocol,
};

/// Codec for our application-bytes request/response.
/// Request and response are both `Vec<u8>` — opaque to the network layer.
#[derive(Clone, Default)]
pub struct GhostMessageCodec;

#[async_trait::async_trait]
impl request_response::Codec for GhostMessageCodec {
    type Protocol = StreamProtocol;
    type Request = Vec<u8>;
    type Response = Vec<u8>;

    async fn read_request<T>(
        &mut self,
        _proto: &Self::Protocol,
        io: &mut T,
    ) -> std::io::Result<Self::Request>
    where
        T: futures::AsyncRead + Unpin + Send,
    {
        use futures::AsyncReadExt;
        let mut buf = Vec::new();
        io.read_to_end(&mut buf).await?;
        Ok(buf)
    }

    async fn read_response<T>(
        &mut self,
        _proto: &Self::Protocol,
        io: &mut T,
    ) -> std::io::Result<Self::Response>
    where
        T: futures::AsyncRead + Unpin + Send,
    {
        use futures::AsyncReadExt;
        let mut buf = Vec::new();
        io.read_to_end(&mut buf).await?;
        Ok(buf)
    }

    async fn write_request<T>(
        &mut self,
        _proto: &Self::Protocol,
        io: &mut T,
        req: Self::Request,
    ) -> std::io::Result<()>
    where
        T: futures::AsyncWrite + Unpin + Send,
    {
        use futures::AsyncWriteExt;
        io.write_all(&req).await?;
        io.close().await?;
        Ok(())
    }

    async fn write_response<T>(
        &mut self,
        _proto: &Self::Protocol,
        io: &mut T,
        resp: Self::Response,
    ) -> std::io::Result<()>
    where
        T: futures::AsyncWrite + Unpin + Send,
    {
        use futures::AsyncWriteExt;
        io.write_all(&resp).await?;
        io.close().await?;
        Ok(())
    }
}

/// The Ghost application stream protocol identifier.
pub const GHOST_PROTOCOL: StreamProtocol = StreamProtocol::new("/ghost/v1");

/// Composed network behaviour for Ghost nodes.
///
/// Event enum `GhostBehaviourEvent` is generated by `#[derive(NetworkBehaviour)]`
/// with variants: `Kad`, `Identify`, `Messages`.
#[derive(NetworkBehaviour)]
pub struct GhostBehaviour {
    pub kad: kad::Behaviour<MemoryStore>,
    pub identify: identify::Behaviour,
    pub messages: request_response::Behaviour<GhostMessageCodec>,
    pub autonat: autonat::Behaviour,
    /// Circuit relay v2 client: lets us reserve a relay slot so peers can
    /// reach us via /p2p/<relay>/p2p-circuit when direct dial fails.
    pub relay_client: relay::client::Behaviour,
    /// DCUtR (Direct Connection Upgrade through Relay): once a relayed
    /// connection exists, both peers perform synchronised UDP hole-punching
    /// to upgrade to a direct connection.
    pub dcutr: dcutr::Behaviour,
    /// Ping keeps idle relay connections from being garbage-collected and
    /// supplies a keep-alive over the request-response idle timer.
    pub ping: ping::Behaviour,
}

impl GhostBehaviour {
    /// Construct a fresh behaviour for the given local `PeerId`/`Keypair`.
    ///
    /// Kademlia starts in **server** mode so this node stores records for the
    /// DHT (peer-discovery requires that real Ghost nodes participate in the
    /// DHT, not just query it). AutoNAT runs as both client (asks peers if our
    /// external address is reachable) and server (answers other peers' probes).
    /// Relay client + DCUtR enable cross-NAT communication: when direct dial
    /// fails, peers fall back to a relayed connection and immediately try
    /// to hole-punch via DCUtR for a direct path.
    pub fn new(
        local_peer_id: PeerId,
        kp: &Keypair,
        relay_client_behaviour: relay::client::Behaviour,
    ) -> Self {
        let kad_store = MemoryStore::new(local_peer_id);
        let kad_config = kad::Config::default();
        let mut kad = kad::Behaviour::with_config(local_peer_id, kad_store, kad_config);
        // Server mode: we will host records for other peers in addition to our own.
        kad.set_mode(Some(kad::Mode::Server));

        // identify::Config::new takes (protocol_version: String, local_public_key: PublicKey).
        let identify_config = identify::Config::new("/ghost/v1".to_string(), kp.public());
        let identify = identify::Behaviour::new(identify_config);

        // request_response::Behaviour::new requires TCodec: Default + Clone.
        let messages = request_response::Behaviour::<GhostMessageCodec>::new(
            std::iter::once((GHOST_PROTOCOL, ProtocolSupport::Full)),
            request_response::Config::default(),
        );

        // AutoNAT defaults are conservative (60s probe interval, server enabled).
        let autonat = autonat::Behaviour::new(local_peer_id, autonat::Config::default());

        let dcutr = dcutr::Behaviour::new(local_peer_id);
        let ping = ping::Behaviour::new(ping::Config::default());

        Self {
            kad,
            identify,
            messages,
            autonat,
            relay_client: relay_client_behaviour,
            dcutr,
            ping,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::identity::libp2p_keypair_from_ik;
    use ghost_identity::IdentityKey;

    #[test]
    fn behaviour_constructs() {
        let ik = IdentityKey::generate();
        let kp = libp2p_keypair_from_ik(&ik).unwrap();
        let peer_id = PeerId::from(kp.public());
        // Test doesn't exercise the relay client transport; instantiating
        // its Behaviour requires a swarm-side handle from SwarmBuilder, so
        // we construct a dummy one via the public API. The tests only
        // verify that GhostBehaviour compiles + the types match.
        let (_relay_transport, relay_behaviour) = relay::client::new(peer_id);
        let _b = GhostBehaviour::new(peer_id, &kp, relay_behaviour);
        // _relay_transport would be wired into SwarmBuilder via with_relay_client
        // in real swarm setup; here we just discard it.
        let _ = _relay_transport;
    }
}
