//! Composed libp2p NetworkBehaviour for Ghost.
//!
//! Combines: Kademlia (DHT), Identify (peer protocol info), RequestResponse (raw bytes).

use libp2p::{
    identify,
    identity::Keypair,
    kad::{self, store::MemoryStore},
    request_response::{self, ProtocolSupport},
    swarm::NetworkBehaviour,
    PeerId, StreamProtocol,
};

/// Codec for our application-bytes request/response.
/// Request and response are both `Vec<u8>` — opaque to the network layer.
#[derive(Clone, Default)]
pub struct GhostMessageCodec;

#[async_trait::async_trait]
impl request_response::Codec for GhostMessageCodec {
    type Protocol = StreamProtocol;
    type Request = Vec<u8>;
    type Response = Vec<u8>;

    async fn read_request<T>(
        &mut self,
        _proto: &Self::Protocol,
        io: &mut T,
    ) -> std::io::Result<Self::Request>
    where
        T: futures::AsyncRead + Unpin + Send,
    {
        use futures::AsyncReadExt;
        let mut buf = Vec::new();
        io.read_to_end(&mut buf).await?;
        Ok(buf)
    }

    async fn read_response<T>(
        &mut self,
        _proto: &Self::Protocol,
        io: &mut T,
    ) -> std::io::Result<Self::Response>
    where
        T: futures::AsyncRead + Unpin + Send,
    {
        use futures::AsyncReadExt;
        let mut buf = Vec::new();
        io.read_to_end(&mut buf).await?;
        Ok(buf)
    }

    async fn write_request<T>(
        &mut self,
        _proto: &Self::Protocol,
        io: &mut T,
        req: Self::Request,
    ) -> std::io::Result<()>
    where
        T: futures::AsyncWrite + Unpin + Send,
    {
        use futures::AsyncWriteExt;
        io.write_all(&req).await?;
        io.close().await?;
        Ok(())
    }

    async fn write_response<T>(
        &mut self,
        _proto: &Self::Protocol,
        io: &mut T,
        resp: Self::Response,
    ) -> std::io::Result<()>
    where
        T: futures::AsyncWrite + Unpin + Send,
    {
        use futures::AsyncWriteExt;
        io.write_all(&resp).await?;
        io.close().await?;
        Ok(())
    }
}

/// The Ghost application stream protocol identifier.
pub const GHOST_PROTOCOL: StreamProtocol = StreamProtocol::new("/ghost/v1");

/// Composed network behaviour for Ghost nodes.
///
/// Event enum `GhostBehaviourEvent` is generated by `#[derive(NetworkBehaviour)]`
/// with variants: `Kad`, `Identify`, `Messages`.
#[derive(NetworkBehaviour)]
pub struct GhostBehaviour {
    pub kad: kad::Behaviour<MemoryStore>,
    pub identify: identify::Behaviour,
    pub messages: request_response::Behaviour<GhostMessageCodec>,
}

impl GhostBehaviour {
    /// Construct a fresh behaviour for the given local `PeerId`/`Keypair`.
    pub fn new(local_peer_id: PeerId, kp: &Keypair) -> Self {
        let kad_store = MemoryStore::new(local_peer_id);
        // kad::Config::default() uses the default Kademlia protocol name.
        let kad_config = kad::Config::default();
        let kad = kad::Behaviour::with_config(local_peer_id, kad_store, kad_config);

        // identify::Config::new takes (protocol_version: String, local_public_key: PublicKey).
        let identify_config = identify::Config::new("/ghost/v1".to_string(), kp.public());
        let identify = identify::Behaviour::new(identify_config);

        // request_response::Behaviour::new requires TCodec: Default + Clone.
        let messages = request_response::Behaviour::<GhostMessageCodec>::new(
            std::iter::once((GHOST_PROTOCOL, ProtocolSupport::Full)),
            request_response::Config::default(),
        );

        Self {
            kad,
            identify,
            messages,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::identity::libp2p_keypair_from_ik;
    use ghost_identity::IdentityKey;

    #[test]
    fn behaviour_constructs() {
        let ik = IdentityKey::generate();
        let kp = libp2p_keypair_from_ik(&ik).unwrap();
        let peer_id = PeerId::from(kp.public());
        let _b = GhostBehaviour::new(peer_id, &kp);
    }
}
